### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by LSalamiUnipd** [4ourSquared/LumosMinima-code#1]
- [x] AreaSingleView
- [x] AreaTable
- [x] Content
- [x] EditAreaForm
- [x] EditLampForm
- [x] EditSensorForm
- [x] Footer
- [x] Header
- [x] LampCard
- [x] LampGuastiPage
- [x] LampGuastiTable
- [x] LampSingleView
- [x] LampTable
- [x] LoginPage
- [x] NewAreaForm
- [x] NewAreaPage
- [x] NewLampForm
- [x] NewLampPage
- [x] NewSensorForm
- [x] NewSensorPage
- [x] PageFullView
- [x] SensorSignleView
- [x] SensorTable

**Comment by matnut2** [comment]
I test completi di Footer e Content li ho fatti io e già buttati sul dev. Parzialmente c'è anche un piccolo test di LoginPage

**Comment by nicolasalberti00** [comment]
Close con le issue #53 #54
