### ISSUE TITLE
Grafica

### ISSUE THREAD

**Issue by LSalamiUnipd** [4ourSquared/LumosMinima-code#4]
- [x] Aggiungere margine pagine aggiunta
- [x] Aggiungere margine pagine modifica
- [x] Grafica mobile
- [x] Colorare in grigio campi non modificabili

**Comment by nicolasalberti00** [comment]
Manca la Grafica Mobile, ma molti degli aggiornamenti sono in #38

**Comment by matnut2** [comment]
Chiuso con #47
